### ISSUE TITLE
Some errors on javascript/python

### ISSUE THREAD

**Issue by riemers** [peternijssen/lovelace-postnl#8]
```Error while setting up platform postnl
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/postnl/sensor.py", line 34, in setup_platform
    from postnlpy.postnlapi import PostnlApi
ModuleNotFoundError: No module named 'postnlpy'
```

But if i go into my container and run it like "python sensor.py" i don't get any error message i would assume i would get them there too.

```postnl-card.js:102:22 Uncaught ReferenceError: LitElement is not defined```

Might be because the component is not loaded

**Comment by peternijssen** [comment]
You don't actually have to run the file. You have to restart HA and then it should automatically load this custom component.

**Comment by peternijssen** [comment]
Solved the error through Discord. Made changes to both the python files as within this repository.
